# Generated by Django 3.1.3 on 2021-04-15 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realbar',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 6, 0, 59, 834710, tzinfo=utc), null=True),
        ),
    ]
