# Generated by Django 3.1.3 on 2021-04-15 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0002_auto_20210415_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realbar',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 6, 49, 35, 337968, tzinfo=utc), null=True),
        ),
    ]
